#!/usr/bin/env ruby

require 'logger'
require 'optparse'

@options = { :log_level => 'info' }
@opt_parser = OptionParser.new do |opts|
  opts.banner = "#{File.basename($0)}: (-l [log-level]) (-h [help])"

  opts.on('-l', '--log-level <level>', 'Log level verbosity') do |log_level|
    @options[:log_level] = log_level
  end

  opts.on('-h', '--help', 'Display help information') do
    abort(opts)
  end
end
@opt_parser.parse!

def fail(msg = '')
  abort([msg, @opt_parser.banner].join("\n"))
end

@logger = Logger.new(STDERR)
@logger.level = Logger.const_get(@options[:log_level].upcase)
@script_name = File.basename($0)

############# TODO #############
## Executable logic goes here ##
################################

@logger.info(@script_name) { 'done' }
